### ISSUE TITLE
Automations not working | Code update to latest version of HA

### ISSUE THREAD

**Issue by jkup39** [alengwenus/hass_esp_irrigation#4]
Hi,
I came across your project the other day and am fascinated. I have updated everything to the latest version of ESPHome and HA and everything is running. However, I have not yet been able to get the zone automation and the skip days automation to work. Maybe you could take another look at it, unfortunately I'm at a loss.
In my opinion, it must be due to the comparison of the time (hass_time) and the state of the set time (zoneX_start).state.

Greetings from and to Lingen!

**Comment by alengwenus** [comment]
I'm on 2024.7.2 (ESPHome) and 2024.7.3 (Core). Unfortunately I cannot reproduce your issue. The automations and time comparisons work perfectly for me. Same for the skipped days.
Please make sure that the automation main switch is on.
Could you verify if your Home Assistant time/timezone is set correctly? The irrigation controller syncs to it regularily once it's available.

**Comment by jkup39** [comment]
Hi thanks for the quick answer.
With the main switch for the automations you mean the GPIO pin right? I have actually activated it. I'll take a closer look later.
I'll be in touch.

**Comment by alengwenus** [comment]
No, I was referring to the automation_enabled (template) switch.

**Comment by jkup39** [comment]
Ah nevermind, your right.  I've checked the template switch, it indeed was disabled xD. Now i have it enabled and shown in the dashboard. Thx much for your help and for sharing your awesome project. Now I can enjoy my vacation without any trouble with my plants!
